name: OQuaRE - Sanity check

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print hello
        run: echo "GitHub Actions working"
