name: OQuaRE - Evaluación de Ontologías

on:
  workflow_dispatch:
  push:
    paths:
      - 'ontologies/**'

permissions:
  contents: write

jobs:
  oquare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Ejecutar OQuaRE
        uses: tecnomod-um/oquare-metrics@v3.0
        with:
          ontology-folders: "ontologies"
          contents-folder: "OQuaRE"
          reasoner: "ELK"

